from model.catalogs.currency import Currency
from model.catalogs.food_restriction import FoodRestriction
from model.catalogs.licensed_medicine import *
from model.catalogs.pathological_background_family import *
from model.catalogs.pathological_background import *
from model.catalogs.payment_account import *
from model.catalogs.staff_role import *
from model.catalogs.vaccine import *
from model.catalogs.constant import *