from model.prueba import *
from model.second import *
from model.catalogs import *
from model.campers import *
from model.camps import *
#from model.prueba_libros import *
from model.payments import *
from model.staffs import *
from model.mailings import *
from model.medical import *
from model.role import *
from model.user import *
from model.permission import *
from model.trainings import *
from model.trophies import *
from model.groupings import *
from model.mercadopago import *