"""empty message

Revision ID: 3b74267633d2
Revises: 
Create Date: 2023-03-23 03:12:08.410912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b74267633d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prueba',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_prueba', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prueba_id'), 'prueba', ['id'], unique=False)
    op.create_table('second',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_second', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_second_id'), 'second', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_second_id'), table_name='second')
    op.drop_table('second')
    op.drop_index(op.f('ix_prueba_id'), table_name='prueba')
    op.drop_table('prueba')
    # ### end Alembic commands ###
