"""empty message

Revision ID: 79e30bf11996
Revises: 
Create Date: 2023-11-03 02:19:58.072686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e30bf11996'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campers_camperrecords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attend', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camps_camp_payments_accounts',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('paymentaccounts_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_id', 'paymentaccounts_id')
    )
    op.create_index(op.f('ix_camps_camp_payments_accounts_camp_id'), 'camps_camp_payments_accounts', ['camp_id'], unique=False)
    op.create_index(op.f('ix_camps_camp_payments_accounts_paymentaccounts_id'), 'camps_camp_payments_accounts', ['paymentaccounts_id'], unique=False)
    op.create_index(op.f('ix_camps_camp_payments_accounts_uid'), 'camps_camp_payments_accounts', ['uid'], unique=True)
    op.create_table('camps_location',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('contact', sa.String(length=512), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camps_location_uid'), 'camps_location', ['uid'], unique=True)
    op.create_table('camps_season',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camps_season_uid'), 'camps_season', ['uid'], unique=True)
    op.create_table('camps_training',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('photo', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camps_training_uid'), 'camps_training', ['uid'], unique=True)
    op.create_table('catalogs_constant',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.String(length=512), nullable=True),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogs_constant_uid'), 'catalogs_constant', ['uid'], unique=True)
    op.create_table('catalogs_currency',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('acronyms', sa.String(length=10), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogs_currency_uid'), 'catalogs_currency', ['uid'], unique=True)
    op.create_table('catalogs_payment_account',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('bank', sa.String(length=30), nullable=False),
    sa.Column('account_number', sa.String(length=10), nullable=False),
    sa.Column('clabe_number', sa.String(length=18), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogs_payment_account_uid'), 'catalogs_payment_account', ['uid'], unique=True)
    op.create_table('catalogs_staff_role',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('payment', sa.Float(precision=2), nullable=True),
    sa.Column('color', sa.String(length=15), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogs_staff_role_uid'), 'catalogs_staff_role', ['uid'], unique=True)
    op.create_table('payments_paymentmethod',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_paymentmethod_uid'), 'payments_paymentmethod', ['uid'], unique=True)
    op.create_table('payments_paymenttransactiontype',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_paymenttransactiontype_uid'), 'payments_paymenttransactiontype', ['uid'], unique=True)
    op.create_table('prueba',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_prueba', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prueba_id'), 'prueba', ['id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_table('second',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_second', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_second_id'), 'second', ['id'], unique=False)
    op.create_table('staff_userrecords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attend', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camps_trainingevent',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('open_enrollment', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['camps_season.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['camps_training.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camps_trainingevent_uid'), 'camps_trainingevent', ['uid'], unique=True)
    op.create_table('catalogs_food_restriction',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('assigned', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned'], ['catalogs_constant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogs_food_restriction_uid'), 'catalogs_food_restriction', ['uid'], unique=True)
    op.create_table('catalogs_licensed_medicine',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('assigned', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned'], ['catalogs_constant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogs_licensed_medicine_uid'), 'catalogs_licensed_medicine', ['uid'], unique=True)
    op.create_table('catalogs_pathological_background',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('assigned', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned'], ['catalogs_constant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogs_pathological_background_uid'), 'catalogs_pathological_background', ['uid'], unique=True)
    op.create_table('catalogs_pathological_background_family',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('assigned', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned'], ['catalogs_constant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogs_pathological_background_family_uid'), 'catalogs_pathological_background_family', ['uid'], unique=True)
    op.create_table('catalogs_vaccine',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('assigned', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned'], ['catalogs_constant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogs_vaccine_uid'), 'catalogs_vaccine', ['uid'], unique=True)
    op.create_table('mailing_emailtemplate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_type', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_type'], ['catalogs_constant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('icon', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('is_coordinator', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_employee', sa.Boolean(), nullable=False),
    sa.Column('target', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('new_window', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_is_active'), 'permission', ['is_active'], unique=False)
    op.create_index(op.f('ix_permission_is_admin'), 'permission', ['is_admin'], unique=False)
    op.create_index(op.f('ix_permission_is_coordinator'), 'permission', ['is_coordinator'], unique=False)
    op.create_index(op.f('ix_permission_is_employee'), 'permission', ['is_employee'], unique=False)
    op.create_index(op.f('ix_permission_new_window'), 'permission', ['new_window'], unique=False)
    op.create_index(op.f('ix_permission_role_id'), 'permission', ['role_id'], unique=False)
    op.create_table('trophy_trophy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=False),
    sa.Column('photo', sa.String(length=512), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('trophy_type', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trophy_type'], ['catalogs_constant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('hashed_pass', sa.String(length=200), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_coordinator', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_employee', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_role_id'), 'user', ['role_id'], unique=False)
    op.create_table('campers_parent',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('toku_id', sa.String(length=512), nullable=True),
    sa.Column('tutor_name', sa.String(length=512), nullable=False),
    sa.Column('tutor_lastname_father', sa.String(length=512), nullable=False),
    sa.Column('tutor_lastname_mother', sa.String(length=512), nullable=True),
    sa.Column('tutor_cellphone', sa.String(length=30), nullable=False),
    sa.Column('tutor_home_phone', sa.String(length=30), nullable=True),
    sa.Column('tutor_work_phone', sa.String(length=30), nullable=True),
    sa.Column('contact_name', sa.String(length=512), nullable=False),
    sa.Column('contact_lastname_father', sa.String(length=512), nullable=False),
    sa.Column('contact_lastname_mother', sa.String(length=512), nullable=True),
    sa.Column('contact_cellphone', sa.String(length=30), nullable=False),
    sa.Column('contact_home_phone', sa.String(length=30), nullable=True),
    sa.Column('contact_work_phone', sa.String(length=30), nullable=True),
    sa.Column('contact_email', sa.String(length=75), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campers_parent_uid'), 'campers_parent', ['uid'], unique=True)
    op.create_table('campers_school',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('contact', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('cellphone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('contact_second_name', sa.String(length=512), nullable=True),
    sa.Column('contact_second_phone', sa.String(length=100), nullable=True),
    sa.Column('contact_second_cellphone', sa.String(length=100), nullable=True),
    sa.Column('contact_second_email', sa.String(length=512), nullable=True),
    sa.Column('contact_third_name', sa.String(length=512), nullable=True),
    sa.Column('contact_third_phone', sa.String(length=100), nullable=True),
    sa.Column('contact_third_cellphone', sa.String(length=100), nullable=True),
    sa.Column('contact_third_email', sa.String(length=512), nullable=True),
    sa.Column('verify', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['login_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campers_school_uid'), 'campers_school', ['uid'], unique=True)
    op.create_table('staff_staff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('lastname_father', sa.String(length=512), nullable=False),
    sa.Column('lastname_mother', sa.String(length=512), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=512), nullable=True),
    sa.Column('curp', sa.String(length=100), nullable=False),
    sa.Column('rfc', sa.String(length=100), nullable=True),
    sa.Column('cellphone', sa.String(length=30), nullable=False),
    sa.Column('home_phone', sa.String(length=30), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('affliction', sa.Text(), nullable=True),
    sa.Column('blood_type', sa.String(length=50), nullable=True),
    sa.Column('drug_allergies', sa.Text(), nullable=True),
    sa.Column('other_allergies', sa.Text(), nullable=True),
    sa.Column('nocturnal_disorders', sa.Text(), nullable=True),
    sa.Column('phobias', sa.Text(), nullable=True),
    sa.Column('drugs', sa.Text(), nullable=True),
    sa.Column('prohibited_foods', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('employee', sa.Boolean(), nullable=False),
    sa.Column('coordinator', sa.Boolean(), nullable=False),
    sa.Column('cv', sa.String(length=512), nullable=True),
    sa.Column('facebook', sa.String(length=50), nullable=False),
    sa.Column('staff_contact_name', sa.String(length=512), nullable=True),
    sa.Column('staff_contact_relation', sa.String(length=512), nullable=True),
    sa.Column('staff_contact_homephone', sa.String(length=512), nullable=True),
    sa.Column('staff_contact_cellphone', sa.String(length=512), nullable=True),
    sa.Column('employee_email_send', sa.Boolean(), nullable=False),
    sa.Column('login_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gender_id'], ['catalogs_constant.id'], ),
    sa.ForeignKeyConstraint(['login_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['staff_userrecords.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['camps_season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trophy_trophystaff',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('trophy_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['camps_season.id'], ),
    sa.ForeignKeyConstraint(['trophy_id'], ['trophy_trophy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campers_camper',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('lastname_father', sa.String(length=512), nullable=False),
    sa.Column('photo', sa.String(length=512), nullable=False),
    sa.Column('lastname_mother', sa.String(length=512), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('height', sa.Float(precision=53), nullable=False),
    sa.Column('weight', sa.Float(precision=53), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('school_other', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('can_swim', sa.Integer(), nullable=False),
    sa.Column('affliction', sa.Text(), nullable=False),
    sa.Column('blood_type', sa.Integer(), nullable=False),
    sa.Column('temporal_blood_type', sa.String(length=15), nullable=True),
    sa.Column('heart_problems', sa.Text(), nullable=False),
    sa.Column('psicology_treatments', sa.Text(), nullable=False),
    sa.Column('prevent_activities', sa.Text(), nullable=False),
    sa.Column('drug_allergies', sa.Text(), nullable=False),
    sa.Column('other_allergies', sa.Text(), nullable=False),
    sa.Column('nocturnal_disorders', sa.Text(), nullable=False),
    sa.Column('phobias', sa.Text(), nullable=False),
    sa.Column('drugs', sa.Text(), nullable=False),
    sa.Column('doctor_precall', sa.Boolean(), nullable=False),
    sa.Column('prohibited_foods', sa.Text(), nullable=False),
    sa.Column('comments_admin', sa.Text(), nullable=True),
    sa.Column('insurance', sa.Boolean(), nullable=True),
    sa.Column('insurance_company', sa.String(length=512), nullable=True),
    sa.Column('insurance_number', sa.String(length=512), nullable=True),
    sa.Column('security_social_number', sa.String(length=512), nullable=True),
    sa.Column('contact_name', sa.String(length=512), nullable=False),
    sa.Column('contact_relation', sa.String(length=512), nullable=False),
    sa.Column('contact_homephone', sa.String(length=512), nullable=False),
    sa.Column('contact_cellphone', sa.String(length=512), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blood_type'], ['catalogs_constant.id'], ),
    sa.ForeignKeyConstraint(['can_swim'], ['catalogs_constant.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['catalogs_constant.id'], ),
    sa.ForeignKeyConstraint(['grade'], ['catalogs_constant.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['campers_parent.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['campers_camperrecords.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['campers_school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camps_camp',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_registration', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_registration', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration', sa.Boolean(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('special_message', sa.Text(), nullable=True),
    sa.Column('special_message_admin', sa.Text(), nullable=True),
    sa.Column('public_price', sa.Float(precision=53), nullable=True),
    sa.Column('show_payment_parent', sa.Boolean(), nullable=False),
    sa.Column('show_rebate_parent', sa.Boolean(), nullable=False),
    sa.Column('show_paypal_button', sa.Boolean(), nullable=False),
    sa.Column('show_payment_order', sa.Boolean(), nullable=False),
    sa.Column('reminder_camp_days', sa.Integer(), nullable=False),
    sa.Column('reminder_discount_days', sa.Integer(), nullable=False),
    sa.Column('insurance', sa.Float(precision=53), nullable=True),
    sa.Column('venue', sa.String(length=250), nullable=False),
    sa.Column('photo_url', sa.String(length=200), nullable=True),
    sa.Column('photo_password', sa.String(length=100), nullable=False),
    sa.Column('medical_report', sa.String(length=512), nullable=True),
    sa.Column('occupancy_camp', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('general_camp', sa.Boolean(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['catalogs_currency.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['camps_location.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['campers_school.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['camps_season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camps_camp_uid'), 'camps_camp', ['uid'], unique=True)
    op.create_table('camps_staffintraining',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assist', sa.Boolean(), nullable=False),
    sa.Column('confirmed_staff', sa.Boolean(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('training_event_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_staff.id'], ),
    sa.ForeignKeyConstraint(['training_event_id'], ['camps_trainingevent.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_event_id', 'staff_id')
    )
    op.create_index(op.f('ix_camps_staffintraining_uid'), 'camps_staffintraining', ['uid'], unique=True)
    op.create_table('staff_staff_food_restriction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('food_restriction_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['food_restriction_id'], ['catalogs_food_restriction.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_staff.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'food_restriction_id')
    )
    op.create_table('staff_staff_vaccines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('vaccine_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_staff.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['vaccine_id'], ['catalogs_vaccine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'vaccine_id')
    )
    op.create_table('staff_staffcomment',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('show_to', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['show_to'], ['catalogs_constant.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_staff.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_staffcomment_uid'), 'staff_staffcomment', ['uid'], unique=True)
    op.create_table('trophy_trophystaff_holder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trophystaff_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_staff.id'], ),
    sa.ForeignKeyConstraint(['trophystaff_id'], ['trophy_trophystaff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trophystaff_id', 'staff_id')
    )
    op.create_table('campers_camper_food_restriction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camper_id', sa.Integer(), nullable=True),
    sa.Column('food_restriction_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['camper_id'], ['campers_camper.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['food_restriction_id'], ['catalogs_food_restriction.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_restriction_id', 'camper_id')
    )
    op.create_table('campers_camper_licensed_medicine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camper_id', sa.Integer(), nullable=True),
    sa.Column('licensed_medicine_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['camper_id'], ['campers_camper.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['licensed_medicine_id'], ['catalogs_licensed_medicine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licensed_medicine_id', 'camper_id')
    )
    op.create_table('campers_camper_pathological_background',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camper_id', sa.Integer(), nullable=True),
    sa.Column('pathological_background_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['camper_id'], ['campers_camper.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['pathological_background_id'], ['catalogs_pathological_background.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pathological_background_id', 'camper_id')
    )
    op.create_table('campers_camper_pathological_background_family',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camper_id', sa.Integer(), nullable=True),
    sa.Column('pathological_background_family_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['camper_id'], ['campers_camper.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['pathological_background_family_id'], ['catalogs_pathological_background_family.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pathological_background_family_id', 'camper_id')
    )
    op.create_table('campers_camper_vaccines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camper_id', sa.Integer(), nullable=True),
    sa.Column('vaccine_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['camper_id'], ['campers_camper.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['vaccine_id'], ['catalogs_vaccine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camper_id', 'vaccine_id')
    )
    op.create_table('campers_campercomment',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('show_to', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('camper_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps_camp.id'], ),
    sa.ForeignKeyConstraint(['camper_id'], ['campers_camper.id'], ),
    sa.ForeignKeyConstraint(['show_to'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campers_campercomment_uid'), 'campers_campercomment', ['uid'], unique=True)
    op.create_table('camps_campdiscount',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('amount', sa.Float(precision=53), nullable=False),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps_camp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camps_campdiscount_uid'), 'camps_campdiscount', ['uid'], unique=True)
    op.create_table('camps_camperincamp',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('payment_balance', sa.Float(precision=53), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('camper_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps_camp.id'], ),
    sa.ForeignKeyConstraint(['camper_id'], ['campers_camper.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['status'], ['catalogs_constant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_id', 'camper_id')
    )
    op.create_index(op.f('ix_camps_camperincamp_uid'), 'camps_camperincamp', ['uid'], unique=True)
    op.create_table('camps_campextracharge',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('price', sa.Float(precision=53), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps_camp.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['catalogs_currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camps_campextracharge_uid'), 'camps_campextracharge', ['uid'], unique=True)
    op.create_table('camps_checkpoint',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps_camp.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('camp_id', 'name')
    )
    op.create_index(op.f('ix_camps_checkpoint_uid'), 'camps_checkpoint', ['uid'], unique=True)
    op.create_table('camps_extraquestion',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps_camp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camps_extraquestion_uid'), 'camps_extraquestion', ['uid'], unique=True)
    op.create_table('camps_staffincamp',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('confirmed_staff', sa.Boolean(), nullable=False),
    sa.Column('assigned_role_id', sa.Integer(), nullable=True),
    sa.Column('camp_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_role_id'], ['catalogs_staff_role.id'], ),
    sa.ForeignKeyConstraint(['camp_id'], ['camps_camp.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_camps_staffincamp_uid'), 'camps_staffincamp', ['uid'], unique=True)
    op.create_table('mailing_campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('camp_parents', sa.Boolean(), nullable=True),
    sa.Column('camp_staff', sa.Boolean(), nullable=True),
    sa.Column('camp_school', sa.Boolean(), nullable=True),
    sa.Column('active_time', sa.String(length=10), nullable=True),
    sa.Column('send', sa.Boolean(), nullable=False),
    sa.Column('camp_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('send_type_id', sa.Integer(), nullable=False),
    sa.Column('training_event_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps_camp.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['camps_season.id'], ),
    sa.ForeignKeyConstraint(['send_type_id'], ['catalogs_constant.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['mailing_emailtemplate.id'], ),
    sa.ForeignKeyConstraint(['training_event_id'], ['camps_training.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments_payment',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_amount', sa.Float(precision=53), nullable=False),
    sa.Column('txn_number', sa.String(length=200), nullable=False),
    sa.Column('camp', sa.Integer(), nullable=False),
    sa.Column('camper', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Integer(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Integer(), nullable=False),
    sa.Column('txn_type', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camp'], ['camps_camp.id'], ),
    sa.ForeignKeyConstraint(['camper'], ['campers_camper.id'], ),
    sa.ForeignKeyConstraint(['currency'], ['catalogs_currency.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['campers_parent.id'], ),
    sa.ForeignKeyConstraint(['payment_method'], ['payments_paymentmethod.id'], ),
    sa.ForeignKeyConstraint(['txn_type'], ['payments_paymenttransactiontype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_payment_uid'), 'payments_payment', ['uid'], unique=True)
    op.create_table('campers_extraanswers',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('camper_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camper_id'], ['campers_camper.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['camps_extraquestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campers_extraanswers_uid'), 'campers_extraanswers', ['uid'], unique=True)
    op.create_table('camps_checkpointcamper',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checkin', sa.Boolean(), nullable=False),
    sa.Column('checkin_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('camper_id', sa.Integer(), nullable=False),
    sa.Column('checkpoint_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camper_id'], ['campers_camper.id'], ),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['camps_checkpoint.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkpoint_id', 'camper_id')
    )
    op.create_index(op.f('ix_camps_checkpointcamper_uid'), 'camps_checkpointcamper', ['uid'], unique=True)
    op.create_table('mailing_camper_campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('camp_id', sa.Integer(), nullable=True),
    sa.Column('camper_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps_camp.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['mailing_campaign.id'], ),
    sa.ForeignKeyConstraint(['camper_id'], ['campers_camper.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailing_school_campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('camp_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps_camp.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['mailing_campaign.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['campers_school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailing_staff_campaign',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('camp_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('training_event_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camp_id'], ['camps_camp.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['mailing_campaign.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['camps_season.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_staff.id'], ),
    sa.ForeignKeyConstraint(['training_event_id'], ['camps_trainingevent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments_camperextracharge',
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('camper_id', sa.Integer(), nullable=False),
    sa.Column('extra_charge_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camper_id'], ['campers_camper.id'], ),
    sa.ForeignKeyConstraint(['extra_charge_id'], ['camps_campextracharge.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extra_charge_id', 'camper_id')
    )
    op.create_index(op.f('ix_payments_camperextracharge_uid'), 'payments_camperextracharge', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_camperextracharge_uid'), table_name='payments_camperextracharge')
    op.drop_table('payments_camperextracharge')
    op.drop_table('mailing_staff_campaign')
    op.drop_table('mailing_school_campaign')
    op.drop_table('mailing_camper_campaign')
    op.drop_index(op.f('ix_camps_checkpointcamper_uid'), table_name='camps_checkpointcamper')
    op.drop_table('camps_checkpointcamper')
    op.drop_index(op.f('ix_campers_extraanswers_uid'), table_name='campers_extraanswers')
    op.drop_table('campers_extraanswers')
    op.drop_index(op.f('ix_payments_payment_uid'), table_name='payments_payment')
    op.drop_table('payments_payment')
    op.drop_table('mailing_campaign')
    op.drop_index(op.f('ix_camps_staffincamp_uid'), table_name='camps_staffincamp')
    op.drop_table('camps_staffincamp')
    op.drop_index(op.f('ix_camps_extraquestion_uid'), table_name='camps_extraquestion')
    op.drop_table('camps_extraquestion')
    op.drop_index(op.f('ix_camps_checkpoint_uid'), table_name='camps_checkpoint')
    op.drop_table('camps_checkpoint')
    op.drop_index(op.f('ix_camps_campextracharge_uid'), table_name='camps_campextracharge')
    op.drop_table('camps_campextracharge')
    op.drop_index(op.f('ix_camps_camperincamp_uid'), table_name='camps_camperincamp')
    op.drop_table('camps_camperincamp')
    op.drop_index(op.f('ix_camps_campdiscount_uid'), table_name='camps_campdiscount')
    op.drop_table('camps_campdiscount')
    op.drop_index(op.f('ix_campers_campercomment_uid'), table_name='campers_campercomment')
    op.drop_table('campers_campercomment')
    op.drop_table('campers_camper_vaccines')
    op.drop_table('campers_camper_pathological_background_family')
    op.drop_table('campers_camper_pathological_background')
    op.drop_table('campers_camper_licensed_medicine')
    op.drop_table('campers_camper_food_restriction')
    op.drop_table('trophy_trophystaff_holder')
    op.drop_index(op.f('ix_staff_staffcomment_uid'), table_name='staff_staffcomment')
    op.drop_table('staff_staffcomment')
    op.drop_table('staff_staff_vaccines')
    op.drop_table('staff_staff_food_restriction')
    op.drop_index(op.f('ix_camps_staffintraining_uid'), table_name='camps_staffintraining')
    op.drop_table('camps_staffintraining')
    op.drop_index(op.f('ix_camps_camp_uid'), table_name='camps_camp')
    op.drop_table('camps_camp')
    op.drop_table('campers_camper')
    op.drop_table('trophy_trophystaff')
    op.drop_table('staff_staff')
    op.drop_index(op.f('ix_campers_school_uid'), table_name='campers_school')
    op.drop_table('campers_school')
    op.drop_index(op.f('ix_campers_parent_uid'), table_name='campers_parent')
    op.drop_table('campers_parent')
    op.drop_index(op.f('ix_user_role_id'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('trophy_trophy')
    op.drop_index(op.f('ix_permission_role_id'), table_name='permission')
    op.drop_index(op.f('ix_permission_new_window'), table_name='permission')
    op.drop_index(op.f('ix_permission_is_employee'), table_name='permission')
    op.drop_index(op.f('ix_permission_is_coordinator'), table_name='permission')
    op.drop_index(op.f('ix_permission_is_admin'), table_name='permission')
    op.drop_index(op.f('ix_permission_is_active'), table_name='permission')
    op.drop_table('permission')
    op.drop_table('mailing_emailtemplate')
    op.drop_index(op.f('ix_catalogs_vaccine_uid'), table_name='catalogs_vaccine')
    op.drop_table('catalogs_vaccine')
    op.drop_index(op.f('ix_catalogs_pathological_background_family_uid'), table_name='catalogs_pathological_background_family')
    op.drop_table('catalogs_pathological_background_family')
    op.drop_index(op.f('ix_catalogs_pathological_background_uid'), table_name='catalogs_pathological_background')
    op.drop_table('catalogs_pathological_background')
    op.drop_index(op.f('ix_catalogs_licensed_medicine_uid'), table_name='catalogs_licensed_medicine')
    op.drop_table('catalogs_licensed_medicine')
    op.drop_index(op.f('ix_catalogs_food_restriction_uid'), table_name='catalogs_food_restriction')
    op.drop_table('catalogs_food_restriction')
    op.drop_index(op.f('ix_camps_trainingevent_uid'), table_name='camps_trainingevent')
    op.drop_table('camps_trainingevent')
    op.drop_table('staff_userrecords')
    op.drop_index(op.f('ix_second_id'), table_name='second')
    op.drop_table('second')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_prueba_id'), table_name='prueba')
    op.drop_table('prueba')
    op.drop_index(op.f('ix_payments_paymenttransactiontype_uid'), table_name='payments_paymenttransactiontype')
    op.drop_table('payments_paymenttransactiontype')
    op.drop_index(op.f('ix_payments_paymentmethod_uid'), table_name='payments_paymentmethod')
    op.drop_table('payments_paymentmethod')
    op.drop_index(op.f('ix_catalogs_staff_role_uid'), table_name='catalogs_staff_role')
    op.drop_table('catalogs_staff_role')
    op.drop_index(op.f('ix_catalogs_payment_account_uid'), table_name='catalogs_payment_account')
    op.drop_table('catalogs_payment_account')
    op.drop_index(op.f('ix_catalogs_currency_uid'), table_name='catalogs_currency')
    op.drop_table('catalogs_currency')
    op.drop_index(op.f('ix_catalogs_constant_uid'), table_name='catalogs_constant')
    op.drop_table('catalogs_constant')
    op.drop_index(op.f('ix_camps_training_uid'), table_name='camps_training')
    op.drop_table('camps_training')
    op.drop_index(op.f('ix_camps_season_uid'), table_name='camps_season')
    op.drop_table('camps_season')
    op.drop_index(op.f('ix_camps_location_uid'), table_name='camps_location')
    op.drop_table('camps_location')
    op.drop_index(op.f('ix_camps_camp_payments_accounts_uid'), table_name='camps_camp_payments_accounts')
    op.drop_index(op.f('ix_camps_camp_payments_accounts_paymentaccounts_id'), table_name='camps_camp_payments_accounts')
    op.drop_index(op.f('ix_camps_camp_payments_accounts_camp_id'), table_name='camps_camp_payments_accounts')
    op.drop_table('camps_camp_payments_accounts')
    op.drop_table('campers_camperrecords')
    # ### end Alembic commands ###
